apiVersion: iter8.tools/v1alpha1
kind: Experiment 
metadata:
  name: demoservice
  labels:
    app.kubernetes.io/name: reviews
spec:
  targetService:
    name: demoservice
    apiVersion: v1 
    baseline: demoservice-v1
    candidate: demoservice-v2
  trafficControl:
    strategy: check_and_increment
    interval: 30s
    trafficStepSize: 20
    maxIterations: 8 #default value = 100
    maxTrafficPercentage: 80 #default value = 50
  analysis:
    analyticsService: "http://iter8-analytics.iter8"
    successCriteria:
      - metricName: iter8_latency
        toleranceType: threshold
        tolerance: 0.2
        sampleSize: 6
