apiVersion: iter8.tools/v1alpha1
kind: Experiment 
metadata:
  name: demoservice
  labels:
    app.kubernetes.io/name: demoservice
spec:
  targetService:
    name: demoservice
    apiVersion: v1 
    baseline: demoservice-v1
    candidate: demoservice-v2
  trafficControl:
    strategy: increment_without_check
    interval: 3s
    trafficStepSize: 2
    maxIterations: 50 #default value = 100
    maxTrafficPercentage: 90 #default value = 50
  routingReference:
    apiversion: networking.istio.io/v1alpha3
    kind: VirtualService
    name: demoservice
  analysis:
    analyticsService: "http://iter8-analytics.iter8"
    successCriteria:
      - metricName: iter8_latency
        toleranceType: threshold
        tolerance: 0.2
        sampleSize: 6
