apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: a-b-deploy-pipeline
spec:
  resources: 
  - name: git-source
    type: git
  - name: docker-image
    type: image
  tasks:
  - name: a-b-deploy
    taskRef:
      name: a-b-deploy
    resources:
      inputs:
      - name: git-source
        resource: git-source
      outputs:
      - name: container-name
        resource: docker-image
